### ISSUE TITLE
Developping data filtering transforms

### ISSUE THREAD

**Issue by TimotheeMickus** [Helsinki-NLP/mammoth#13]
Current preliminary experiments suggest we have datapoints with repeated substrings; likely other quality issues are to be found down the line. It would be useful to means of removing unusable or garbage data (similar to what is done in OpusFilter).

This is something that can be done with transforms (same mechanism as in OpenNMT-py, since that's where it comes from).

Transform objects inherit from `onmt.transforms.Transform`, and have:
1. an `apply` method, that takes as input an  `example` dict containing a `src`and  `tgt` key and return:
    - either `None `(to signal the datapoint was dropped) 
    - or a dict (containing potentially modified copies of `src` and `tgt`, for further preprocessing)
2. an `add_option` and a `_parse_opts` class methods, to declare config arguments and retrieve values as necessary 
3. a `@register_transform` decorator to ensure they are automatically discovered by the rest of the code.

See also [the declaration of `FilterTooLongTransform`](https://github.com/Helsinki-NLP/mammoth/blob/main/onmt/transforms/misc.py#L19C15-L19C15) for a minimal example of how the `filtertoolong` transform is declared in the code.

Ideally, for this enhancement, one would need to:
- [x] create a file `onmt/transforms/filtering.py`
- [x] move everything related to the `FilterTooLongTransform` in `onmt/transforms/misc.py` to this new file
- [x] either modify this transform or create new classes to remove datapoints based on:
    - [x] source length / target length  ratios
    - [x] repeated substrings in source or in target
    - [ ] Levenshtein similarity between source and target
    - [x] whatever else makes sense

**Comment by Waino** [comment]
Note that the transforms are computed online for all training sentence pairs. While this happens in a separate process, and thus can work in parallel with the GPU, it can not be arbitrarily slow or it will fail to produce data fast enough to keep the GPU working at full efficiency.

Computing Levenshtein distance for long strings may not be a good idea in this regard.
